### ISSUE TITLE
Why is Var used instead of Let? 

### ISSUE THREAD

**Issue by dannyenfp** [learn-co-curriculum/js-looping-and-iteration-object-iteration-readme#2]
I'm a bit confused about the documentation for most of these JavaScript reading sections. In most of the previous sections it says NEVER use "VAR" but instead use "let" or "const"... and it always confuses me when "var" is written, but then is referred to as a "let" statement. 

Is this intentional? As it stands, this statement doesn't make sense: "As you might've noticed, for...of allows us to use const instead of let"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @dannyenfp.

We have updated the materials and swapped `var` for `let` in the code snippets. You are correct that there is no reason in these examples to use `var`.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
